# Uncomment this line to define a global platform for your project
platform :ios, '8.1'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'RealmDataBaseObjC' do
pod "Realm"

end

target 'RealmDataBaseObjCTests' do

end

target 'RealmDataBaseObjCUITests' do

end

